language: go
go:
  - 1.x
  - tip

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y haproxy
  - sudo apt-get install apache2-utils

install: true

script:
  - go build ./...
  - ./hack/coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
